spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbcafe
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0508

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
